name = "Raycore"
uuid = "afc56b53-c9a9-482a-a956-d1d800e05559"
version = "0.1.1"
authors = ["Anton Smirnov <tonysmn97@gmail.com>", "Simon Danisch <sdanisch@protonmail.com"]

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
RaycoreMakieExt = "Makie"

[compat]
julia = "1.10"
GeometryBasics = "0.5"
KernelAbstractions = "0.9, 0.10"
LinearAlgebra = "1"
Random = "1"
StaticArrays = "1.9.7"
Statistics = "1"
Makie = "0.24"
Aqua = "0.8"
JET = "0.11"
Test = "1"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[targets]
test = ["Test", "JET", "Aqua"]
